spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: monari-back
  api:
    base-url: http://openAPI.seoul.go.kr:8088
    key: ${SEOUL_API_KEY}
    service-name: ListPublicReservationInstitution
    data-type: json

location:
  init: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  accessToken-expiration-millis: 1800000

aws:
  s3:
    bucket: ${S3_BUCKET_NAME}
    region: ${S3_REGION}
    access-key-id: ${S3_ACCESS_KEY}
    secret-access-key: ${S3_SECRET_KEY}
