spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: monari-back
  api:
    base-url: http://openAPI.seoul.go.kr:8088
    key: ${SEOUL_API_KEY}
    service-name: ListPublicReservationInstitution
    data-type: json
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

location:
  init: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  accessToken-expiration-millis: 1800000