spring:
  application:
    name: monari-back
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  api:
    base-url: http://openAPI.seoul.go.kr:8088
    key: 676e4f796567776133304b6b444764
    service-name: ListPublicReservationInstitution
    data-type: json

location:
  init: true


oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
  secret-key: ${JWT_SECRET_KEY}
  accessToken-expiration-millis: 1800000